[package]
name = "data-tools"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
bzip2 = "0.4.4"
clap = { version = "4.5.8", features = ["derive"] }
indicatif = "0.17.8"
nom = "7.1.3"
quick-xml = "0.35.0"
